"""feat: add routes

Revision ID: 283f5ba4fe96
Revises: 6cb6aa3ec4f9
Create Date: 2025-12-04 01:09:06.017624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283f5ba4fe96'
down_revision: Union[str, Sequence[str], None] = '6cb6aa3ec4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('route_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'entities', 'routes', ['route_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'locations', ['id'])
    op.create_unique_constraint(None, 'routes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='unique')
    op.drop_constraint(None, 'locations', type_='unique')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_column('entities', 'route_id')
    # ### end Alembic commands ###
