"""rename enabled to active

Revision ID: 6cb6aa3ec4f9
Revises: 8f0058de4387
Create Date: 2025-12-02 15:11:54.600102

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cb6aa3ec4f9"
down_revision: Union[str, Sequence[str], None] = "8f0058de4387"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entities",
        sa.Column(
            "active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    op.drop_column("entities", "enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entities",
        sa.Column(
            "enabled",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("entities", "active")
    # ### end Alembic commands ###
