#!/bin/bash
set -e
echo $API_USER_USERNAME
# Use psql to execute the SQL with environment variables injected
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $API_USER_USERNAME WITH PASSWORD '$API_USER_PASSWORD';
    CREATE USER $INGESTION_USER_USERNAME WITH PASSWORD '$INGESTION_USER_PASSWORD';
    CREATE USER $MIGRATION_DB_USER WITH PASSWORD '$MIGRATOR_PASSWORD';

    REVOKE ALL ON DATABASE $POSTGRES_DB FROM PUBLIC;
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $MIGRATION_DB_USER, $INGESTION_USER_USERNAME, $API_USER_USERNAME;

    ALTER SCHEMA public OWNER TO $MIGRATION_DB_USER;
    GRANT USAGE ON SCHEMA public TO $INGESTION_USER_USERNAME, $API_USER_USERNAME;

    ALTER DEFAULT PRIVILEGES FOR ROLE $MIGRATION_DB_USER IN SCHEMA public 
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $API_USER_USERNAME;

    ALTER DEFAULT PRIVILEGES FOR ROLE $MIGRATION_DB_USER IN SCHEMA public 
        GRANT SELECT, INSERT ON TABLES TO $INGESTION_USER_USERNAME;

    ALTER DEFAULT PRIVILEGES FOR ROLE $MIGRATION_DB_USER IN SCHEMA public 
        GRANT USAGE, SELECT ON SEQUENCES TO $API_USER_USERNAME, $INGESTION_USER_USERNAME;

    CREATE EXTENSION IF NOT EXISTS postgis;
    GRANT SELECT ON spatial_ref_sys TO $INGESTION_USER_USERNAME, $API_USER_USERNAME;
EOSQL