"""
AI DECLARATION: GENERATED BY CLAUDE.AI BY ISAAC TAYLOR ON 12/04/26

Ferry Tracker Database Seed Script
===================================
Populates the database with:
  - 3 ferry entities (Torpoint Ferry, Cremyll Ferry, Mayflower Cruise)
  - Realistic GPS telemetry local to Plymouth Sound
  - One API key (printed to console for testing)

Usage:
    pip install sqlalchemy geoalchemy2 psycopg2-binary passlib[argon2]
    python tests/seed_db.py

The script resolves the database URL automatically from your .env file,
walking up from its own location until it finds one. It uses:
    DATABASE_HOST, DATABASE_PORT, DATABASE_NAME, POSTGRES_USER, POSTGRES_PASSWORD

You can still override everything by setting DATABASE_URL in the environment.
"""

import datetime
import os
import secrets
import sys
from pathlib import Path

# Make the project root importable when running as `python tests/seed_db.py`
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from geoalchemy2 import WKTElement
from passlib.context import CryptContext
from sqlalchemy import create_engine
from sqlalchemy.orm import Session

pwd_context = CryptContext(schemes=["argon2"], deprecated="auto")


def load_env_file() -> None:
    """
    Walk up from this file's directory until a .env is found, then load it
    into os.environ (without overwriting variables already set in the shell).
    """
    search = Path(__file__).resolve().parent
    for directory in [search, *search.parents]:
        env_file = directory / ".env"
        if env_file.exists():
            with env_file.open() as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#") or "=" not in line:
                        continue
                    key, _, value = line.partition("=")
                    key = key.strip()
                    value = value.strip().strip('"').strip("'")
                    os.environ.setdefault(key, value)
            print(f"   Loaded .env from {env_file}")
            return
    print("   Warning: no .env file found — relying on environment variables only.")


def build_database_url() -> str:
    """
    Construct a PostgreSQL URL from .env variables, or return DATABASE_URL
    directly if it is already set in the environment.
    """
    if url := os.environ.get("DATABASE_URL"):
        return url

    load_env_file()

    host = "localhost"
    port = "5432"
    name = os.environ.get("DATABASE_NAME") or os.environ.get("POSTGRES_DB")
    user = os.environ.get("POSTGRES_USER")
    password = os.environ.get("POSTGRES_PASSWORD", "")

    missing = [
        k for k, v in {"host": host, "name": name, "user": user}.items() if not v
    ]
    if missing:
        sys.exit(
            f"Error: could not build DATABASE_URL — missing values for: {', '.join(missing)}\n"
            "Check your .env file contains DATABASE_HOST, DATABASE_NAME, "
            "POSTGRES_USER and POSTGRES_PASSWORD."
        )

    return f"postgresql://{user}:{password}@{host}:{port}/{name}"


# ---------------------------------------------------------------------------
# Import your application models.  Adjust the import path to match your
# project layout.  The script assumes it is run from the project root, or
# that the package containing `models` is on PYTHONPATH.
# ---------------------------------------------------------------------------
try:
    from core.models import (
        APIKey,
        Base,
        Entity,
        EntityAttribute,
        GPSTelemetry,
        Location,
        LocationAttribute,
        Point,
        Route,
        RouteStop,
    )
except ImportError as exc:
    sys.exit(
        f"Could not import models: {exc}\n"
        "Edit the import at the top of this script to match your project layout."
    )

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def point_wkt(lon: float, lat: float) -> WKTElement:
    """Return a PostGIS-compatible WKT POINT element (SRID 4326)."""
    return WKTElement(f"POINT({lon} {lat})", srid=4326)


def interpolate_route(
    waypoints: list[tuple[float, float]],
    steps_per_segment: int = 8,
) -> list[tuple[float, float]]:
    """
    Linear interpolation between (lon, lat) waypoints.
    Returns a flat list of (lon, lat) tuples including start/end.
    """
    result = []
    for i in range(len(waypoints) - 1):
        lon1, lat1 = waypoints[i]
        lon2, lat2 = waypoints[i + 1]
        for s in range(steps_per_segment):
            t = s / steps_per_segment
            result.append((lon1 + (lon2 - lon1) * t, lat1 + (lat2 - lat1) * t))
    result.append(waypoints[-1])
    return result


def generate_telemetry(
    entity: Entity,
    positions: list[tuple[float, float]],
    start_time: datetime.datetime,
    interval_seconds: int = 30,
) -> list[GPSTelemetry]:
    """Build GPSTelemetry rows for a sequence of positions."""
    rows = []
    for i, (lon, lat) in enumerate(positions):
        ts = start_time + datetime.timedelta(seconds=i * interval_seconds)
        rows.append(
            GPSTelemetry(
                entity_id=entity.id,
                timestamp=ts,
                geom=point_wkt(lon, lat),
            )
        )
    return rows


def make_api_key() -> tuple[str, str, str]:
    """
    Return (raw_key, hashed_key, prefix).
    The raw key is shown to the user once; only the argon2 hash is stored.
    """
    raw = f"sk_dev_{secrets.token_urlsafe(32)}"
    prefix = raw[:12]
    hashed = pwd_context.hash(raw)
    return raw, hashed, prefix


# ---------------------------------------------------------------------------
# Plymouth Sound geography
# ---------------------------------------------------------------------------
#
# Key coordinates (lon, lat):
#   Devonport / Torpoint ferry slipway (Devon side):  -4.1742, 50.3732
#   Torpoint slipway (Cornwall side):                 -4.1950, 50.3748
#   Cremyll (Cornwall side):                          -4.1840, 50.3557
#   Admiral's Hard, Stonehouse (Devon side):          -4.1680, 50.3610
#   Mayflower Steps, Barbican:                        -4.1420, 50.3680
#   Plymouth Hoe:                                     -4.1440, 50.3660
#   Drake's Island:                                   -4.1580, 50.3620
#   Breakwater fort (outer Sound):                    -4.1480, 50.3500

TORPOINT_DEVON = (-4.1742, 50.3732)
TORPOINT_CORNWALL = (-4.1950, 50.3748)

CREMYLL = (-4.1840, 50.3557)
ADMIRALS_HARD = (-4.1680, 50.3610)

MAYFLOWER_STEPS = (-4.1420, 50.3680)
DRAKES_ISLAND = (-4.1580, 50.3620)
HOE = (-4.1440, 50.3660)
BREAKWATER = (-4.1480, 50.3500)

# ---------------------------------------------------------------------------
# Seed data definitions
# ---------------------------------------------------------------------------

ENTITIES = [
    {
        "name": "Torpoint Ferry No.1",
        "description": (
            "Chain ferry crossing the River Tamar between Devonport and Torpoint. "
            "Operated by Cornwall Council."
        ),
        "type": "Ferry",
        "attributes": [
            {"key": "operator", "value": "Cornwall Council", "datatype": "string"},
            {"key": "capacity_vehicles", "value": "73", "datatype": "integer"},
            {"key": "crossing_minutes", "value": "7", "datatype": "integer"},
            {"key": "vessel_type", "value": "chain_ferry", "datatype": "string"},
            {"key": "call_sign", "value": "TORPOINT1", "datatype": "string"},
        ],
        # Waypoints for one full crossing + return
        "route_waypoints": [
            TORPOINT_DEVON,
            (-4.1790, 50.3737),
            (-4.1840, 50.3742),
            (-4.1895, 50.3746),
            TORPOINT_CORNWALL,
            (-4.1895, 50.3746),
            (-4.1840, 50.3742),
            (-4.1790, 50.3737),
            TORPOINT_DEVON,
        ],
    },
    {
        "name": "Cremyll Ferry",
        "description": (
            "Passenger ferry across the Hamoaze between Stonehouse and Cremyll, "
            "serving Mount Edgcumbe Country Park."
        ),
        "type": "Ferry",
        "attributes": [
            {"key": "operator", "value": "Tamar Cruising", "datatype": "string"},
            {"key": "capacity_passengers", "value": "48", "datatype": "integer"},
            {"key": "crossing_minutes", "value": "5", "datatype": "integer"},
            {"key": "vessel_type", "value": "passenger_launch", "datatype": "string"},
            {"key": "call_sign", "value": "CREMYLL1", "datatype": "string"},
        ],
        "route_waypoints": [
            ADMIRALS_HARD,
            (-4.1720, 50.3595),
            (-4.1760, 50.3578),
            CREMYLL,
            (-4.1760, 50.3578),
            (-4.1720, 50.3595),
            ADMIRALS_HARD,
        ],
    },
    {
        "name": "Mayflower Harbour Cruise",
        "description": (
            "Tourist sightseeing cruise departing Mayflower Steps, circling "
            "Drake's Island and the Plymouth Breakwater."
        ),
        "type": "Cruise",
        "attributes": [
            {"key": "operator", "value": "Plymouth Boat Trips", "datatype": "string"},
            {"key": "capacity_passengers", "value": "80", "datatype": "integer"},
            {"key": "cruise_duration_minutes", "value": "60", "datatype": "integer"},
            {"key": "vessel_type", "value": "pleasure_cruiser", "datatype": "string"},
            {"key": "call_sign", "value": "MHCRUISE1", "datatype": "string"},
        ],
        "route_waypoints": [
            MAYFLOWER_STEPS,
            (-4.1460, 50.3660),
            (-4.1510, 50.3635),
            DRAKES_ISLAND,
            (-4.1560, 50.3575),
            (-4.1500, 50.3510),
            BREAKWATER,
            (-4.1450, 50.3520),
            (-4.1420, 50.3580),
            HOE,
            (-4.1420, 50.3640),
            MAYFLOWER_STEPS,
        ],
    },
]

# Locations (stops / terminals)
LOCATIONS = [
    {
        "name": "Devonport Torpoint Slipway",
        "lon": TORPOINT_DEVON[0],
        "lat": TORPOINT_DEVON[1],
        "attributes": [
            {"key": "type", "value": "ferry_terminal", "datatype": "string"},
            {"key": "side", "value": "Devon", "datatype": "string"},
        ],
    },
    {
        "name": "Torpoint Slipway",
        "lon": TORPOINT_CORNWALL[0],
        "lat": TORPOINT_CORNWALL[1],
        "attributes": [
            {"key": "type", "value": "ferry_terminal", "datatype": "string"},
            {"key": "side", "value": "Cornwall", "datatype": "string"},
        ],
    },
    {
        "name": "Admiral's Hard, Stonehouse",
        "lon": ADMIRALS_HARD[0],
        "lat": ADMIRALS_HARD[1],
        "attributes": [
            {"key": "type", "value": "ferry_terminal", "datatype": "string"},
        ],
    },
    {
        "name": "Cremyll Quay",
        "lon": CREMYLL[0],
        "lat": CREMYLL[1],
        "attributes": [
            {"key": "type", "value": "ferry_terminal", "datatype": "string"},
        ],
    },
    {
        "name": "Mayflower Steps",
        "lon": MAYFLOWER_STEPS[0],
        "lat": MAYFLOWER_STEPS[1],
        "attributes": [
            {"key": "type", "value": "cruise_departure", "datatype": "string"},
        ],
    },
]


# ---------------------------------------------------------------------------
# Main seed function
# ---------------------------------------------------------------------------


def seed(session: Session) -> None:
    print("🌊  Plymouth Ferry Tracker — database seed")
    print("=" * 50)

    # -- Locations -----------------------------------------------------------
    print("\n📍 Creating locations...")
    loc_objects: dict[str, Location] = {}
    for loc_data in LOCATIONS:
        loc = Location(
            name=loc_data["name"],
            geom=point_wkt(loc_data["lon"], loc_data["lat"]),
        )
        for attr in loc_data.get("attributes", []):
            loc.attributes.append(
                LocationAttribute(
                    key=attr["key"],  # type: ignore
                    value=attr["value"],  # type: ignore
                    datatype=attr["datatype"],  # type: ignore
                )
            )
        session.add(loc)
        loc_objects[loc_data["name"]] = loc
    session.flush()
    print(f"   ✓ {len(LOCATIONS)} locations created")

    # -- Entities + telemetry ------------------------------------------------
    print("\n🚢 Creating ferry entities and GPS telemetry...")
    start_time = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(
        hours=2
    )

    for i, entity_data in enumerate(ENTITIES):
        entity = Entity(
            name=entity_data["name"],
            description=entity_data["description"],
            type=entity_data["type"],
        )
        for attr in entity_data["attributes"]:
            entity.attributes.append(
                EntityAttribute(
                    key=attr["key"],  # type: ignore
                    value=attr["value"],  # type: ignore
                    datatype=attr["datatype"],  # type: ignore
                )
            )
        session.add(entity)
        session.flush()  # get entity.id

        # Build interpolated telemetry
        positions = interpolate_route(
            entity_data["route_waypoints"], steps_per_segment=10
        )
        # Stagger start times so vessels aren't perfectly synchronised
        vessel_start = start_time + datetime.timedelta(minutes=i * 12)
        telemetry_rows = generate_telemetry(
            entity, positions, vessel_start, interval_seconds=30
        )
        session.add_all(telemetry_rows)

        print(
            f"   ✓ {entity.name}: {len(telemetry_rows)} telemetry points (uuid: {entity.uuid})"
        )

    session.flush()

    # -- API Key -------------------------------------------------------------
    print("\n🔑 Generating API key...")
    raw_key, hashed_key, prefix = make_api_key()
    api_key = APIKey(
        key=hashed_key,
        label="Test API Key (seed script)",
        prefix=prefix,
        is_active=True,
    )
    session.add(api_key)
    session.flush()

    # -- Commit --------------------------------------------------------------
    session.commit()
    print("\n✅ Database seeded successfully.")
    print("\n" + "=" * 50)
    print("  YOUR TEST API KEY (shown only once — store it safely):")
    print()
    print(f"    {raw_key}")
    print()
    print("  Prefix stored in DB: ", prefix)
    print("  Key ID:              ", api_key.id)
    print("=" * 50 + "\n")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    database_url = build_database_url()
    print(f"   Connecting to: {database_url}\n")
    engine = create_engine(database_url, echo=False)
    with Session(engine) as session:
        seed(session)
