nodename = VerneMQ@127.0.0.1

allow_anonymous = off
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_webhooks = on

vmq_webhooks.auth_on_register.hook = auth_on_register
vmq_webhooks.auth_on_register.endpoint = http://mqtt-auth:8080/auth/register
vmq_webhooks.auth_on_register.base64encode = off

vmq_webhooks.auth_on_subscribe.hook = auth_on_subscribe
vmq_webhooks.auth_on_subscribe.endpoint = http://mqtt-auth:8080/auth/subscribe
vmq_webhooks.auth_on_subscribe.base64encode = off

vmq_webhooks.auth_on_publish.hook = auth_on_publish
vmq_webhooks.auth_on_publish.endpoint = http://mqtt-auth:8080/auth/publish
vmq_webhooks.auth_on_publish.base64encode = off

listener.ssl.default = 0.0.0.0:8883
listener.ssl.default.cafile = /etc/vernemq/certs/ca.crt
listener.ssl.default.certfile = /etc/vernemq/certs/broker.crt
listener.ssl.default.keyfile = /etc/vernemq/certs/broker.key

listener.tcp.default = 0.0.0.0:1883
########## Start ##########
accept_eula=yes
log.console=console
conf_override=true
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 172.21.0.7:1883
listener.ws.default = 172.21.0.7:8080
listener.vmq.clustering = 172.21.0.7:44053
listener.http.metrics = 172.21.0.7:8888
