[env:T-SIM7670G-S3]
platform = espressif32
board = esp32s3box
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB

board_build.partitions = default_16MB.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLILYGO_T_SIM7670G_S3

upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    vshymanskyy/StreamDebugger @ ^1.0.1
    git+https://github.com/knolleary/pubsubclient
