server {
    listen 80;

    # Docker's internal DNS resolver
    resolver 127.0.0.11 valid=30s;
    
    location ~ ^/api/v1/entities/[^/]+/telemetry {
        set $ingestion_backend http://ingestion-server:8080;
        
        proxy_pass $ingestion_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        rewrite ^/api/v1(/.*)$ $1 break;
    }

    location /api/v1/ {
        set $api_backend http://api:8080;
        
        proxy_pass $api_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        rewrite ^/api/v1(/.*)$ $1 break;
    }

    location /api/v1/entities/ws {
        resolver 127.0.0.11 valid=30s;
        set $api_backend http://api:8080;
        proxy_pass $api_backend;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        resolver 127.0.0.11 valid=30s;
        set $frontend http://frontend:8080;
        proxy_pass $frontend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}