"""feat: add sensor tables

Revision ID: 2170b67d4a0c
Revises: 5bb891b35ad4
Create Date: 2026-04-22 19:22:12.912825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2170b67d4a0c'
down_revision: Union[str, Sequence[str], None] = '5bb891b35ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sensor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('mqtt_username', sa.String(length=255), nullable=False),
    sa.Column('mqtt_password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['Entity.id'], name=op.f('fk_Sensor_entity_id_Entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Sensor')),
    sa.UniqueConstraint('mqtt_username', name=op.f('uq_Sensor_mqtt_username')),
    sa.UniqueConstraint('uuid', name=op.f('uq_Sensor_uuid'))
    )
    op.create_table('SensorACL',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('rw', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['Sensor.id'], name=op.f('fk_SensorACL_sensor_id_Sensor'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_SensorACL')),
    sa.UniqueConstraint('sensor_id', 'topic', name=op.f('uq_SensorACL_sensor_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SensorACL')
    op.drop_table('Sensor')
    # ### end Alembic commands ###
