"""feat: add api key

Revision ID: 5bb891b35ad4
Revises: 3b5cc73cf3cb
Create Date: 2026-02-05 17:21:22.788783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb891b35ad4'
down_revision: Union[str, Sequence[str], None] = '3b5cc73cf3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APIKey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('allowed_entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allowed_entity_id'], ['Entity.id'], name=op.f('fk_APIKey_allowed_entity_id_Entity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_APIKey')),
    sa.UniqueConstraint('key', name=op.f('uq_APIKey_key'))
    )
    op.create_index(op.f('ix_APIKey_prefix'), 'APIKey', ['prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_APIKey_prefix'), table_name='APIKey')
    op.drop_table('APIKey')
    # ### end Alembic commands ###
