"""feat: initial database schema

Revision ID: a7dc0a7c0ffe
Revises:
Create Date: 2026-02-02 10:38:17.557518

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7dc0a7c0ffe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "Entity",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Entity")),
        sa.UniqueConstraint("uuid", name=op.f("uq_Entity_uuid")),
    )
    op.create_table(
        "Location",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Location")),
    )
    # op.create_index(
    # "idx_Location_geom", "Location", ["geom"], unique=False, postgresql_using="gist"
    # )
    op.create_table(
        "EntityAttribute",
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("datatype", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["Entity.id"],
            name=op.f("fk_EntityAttribute_parent_id_Entity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_EntityAttribute")),
        sa.UniqueConstraint(
            "parent_id", "key", name=op.f("uq_EntityAttribute_parent_id")
        ),
    )
    op.create_table(
        "GPSTelemetry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["Entity.id"],
            name=op.f("fk_GPSTelemetry_entity_id_Entity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_GPSTelemetry")),
    )
    # op.create_index(
    # "idx_GPSTelemetry_geom",
    # "GPSTelemetry",
    # ["geom"],
    # unique=False,
    # postgresql_using="gist",
    # )
    op.create_index(
        "ix_entity_timestamp", "GPSTelemetry", ["entity_id", "timestamp"], unique=False
    )
    op.create_table(
        "LocationAttribute",
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("datatype", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["Location.id"],
            name=op.f("fk_LocationAttribute_parent_id_Location"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_LocationAttribute")),
        sa.UniqueConstraint(
            "parent_id", "key", name=op.f("uq_LocationAttribute_parent_id")
        ),
    )
    op.create_table(
        "Route",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("start_location_id", sa.Integer(), nullable=False),
        sa.Column("end_location_id", sa.Integer(), nullable=False),
        sa.Column("inverse_route_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["end_location_id"],
            ["Location.id"],
            name=op.f("fk_Route_end_location_id_Location"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["inverse_route_id"],
            ["Route.id"],
            name=op.f("fk_Route_inverse_route_id_Route"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["start_location_id"],
            ["Location.id"],
            name=op.f("fk_Route_start_location_id_Location"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Route")),
        sa.UniqueConstraint("uuid", name=op.f("uq_Route_uuid")),
    )
    op.create_table(
        "EntityOnRoute",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["Entity.id"],
            name=op.f("fk_EntityOnRoute_entity_id_Entity"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["Route.id"],
            name=op.f("fk_EntityOnRoute_route_id_Route"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_EntityOnRoute")),
        sa.UniqueConstraint("entity_id", name=op.f("uq_EntityOnRoute_entity_id")),
    )
    op.create_table(
        "Point",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["Route.id"],
            name=op.f("fk_Point_route_id_Route"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Point")),
    )
    # op.create_index(
    # "idx_Point_geom", "Point", ["geom"], unique=False, postgresql_using="gist"
    # )
    op.create_table(
        "RouteAttribute",
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("datatype", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["Route.id"],
            name=op.f("fk_RouteAttribute_parent_id_Route"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_RouteAttribute")),
        sa.UniqueConstraint(
            "parent_id", "key", name=op.f("uq_RouteAttribute_parent_id")
        ),
    )
    op.create_table(
        "RouteStop",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["Location.id"],
            name=op.f("fk_RouteStop_location_id_Location"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["Route.id"],
            name=op.f("fk_RouteStop_route_id_Route"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_RouteStop")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("RouteStop")
    op.drop_table("RouteAttribute")
    # op.drop_index("idx_Point_geom", table_name="Point", postgresql_using="gist")
    op.drop_table("Point")
    op.drop_table("EntityOnRoute")
    op.drop_table("Route")
    op.drop_table("LocationAttribute")
    op.drop_index("ix_entity_timestamp", table_name="GPSTelemetry")
    # op.drop_index(
    # "idx_GPSTelemetry_geom", table_name="GPSTelemetry", postgresql_using="gist"
    # )
    op.drop_table("GPSTelemetry")
    op.drop_table("EntityAttribute")
    # op.drop_index("idx_Location_geom", table_name="Location", postgresql_using="gist")
    op.drop_table("Location")
    op.drop_table("Entity")
    # ### end Alembic commands ###
